twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: "Aqua Estimate"
        version: "2.8"
        date_update: "29/10/2023"
        google_maps: ""
        recaptcha_public: ''
        recaptcha_private: ''
        mailjet_public: ''
        mailjet_private: ''
        posts_img_directory: '/uploads/images/posts'
        piscines_img_dir: '/uploads/images/piscines'
        esc_img_dir: '/uploads/images/escs'
        color_img_dir: '/uploads/images/colors'

when@test:
    twig:
        strict_variables: true
