version: '3.8'
 
services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=@cu1t3-D1git@Le_202X
            - MYSQL_PASSWORD=Cre@t1ve-3ye_202X
            - MYSQL_DATABASE=cms-db
            - MYSQL_USER=cms-manager
        ports:
            - 3306:3306
    
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: always
        depends_on:
            - db
        ports:
            - 8090:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    web:
        build: .
        ports:
            - 8080:80