version: '3.8'

services:
  database:
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - database
    environment:
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=root
  
  maildev:
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 8081:80
    restart: always
  
  app:
    image: cms-project
    ports:
      - 8080:80
    environment:
      - APP_ENV=prod
      - DATABASE_URL="mysql://root:root@database:3306/cms-projects?serverVersion=5.7&charset=utf8mb4"
      - MAILER_DSN=null://null

volumes:
  db-data: