name: Deploy on Prod

on:
  push:
    branches: 
      - 'main'

jobs:
  web-deploy:
    name: Web-Deploy
    runs-on: ubuntu-latest
    steps:
    # PHP
    # --------------------------------------------------------------------------------------
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
        tools: composer:v2
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
      env:
        update: true
    - name: Check PHP Version
      run: php -v

    # COMPOSER
    # --------------------------------------------------------------------------------------
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install Composer dependencies
      run: composer install

    # PREPARE PROD
    # --------------------------------------------------------------------------------------
    - name: Make production envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_APP_ENV: prod
        envkey_APP_DEBUG: false
        file_name: .env

    # YARN
    # --------------------------------------------------------------------------------------

    # DEPLOY ON SERVER 
    # --------------------------------------------------------------------------------------